# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: searchbox-io/Jest
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Compile the module where the test is, and all modules it depends on...
      run:  mvn clean install -DskipTests -pl jest-common -am
      
    - name: Normal testBasicUriGeneration
      run: mvn -pl jest-common test -Dtest=io.searchbox.indices.RolloverTest#testBasicUriGeneration
    
    - name: Normal testBasicUriWithSettingsGeneration
      run: mvn -pl jest-common test -Dtest=io.searchbox.indices.RolloverTest#testBasicUriWithSettingsGeneration
      
    - name: Nondex testBasicUriGeneration
      run: mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=io.searchbox.indices.RolloverTest#testBasicUriGeneration
      
    - name: Nondex testBasicUriWithSettingsGeneration
      run: mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=io.searchbox.indices.RolloverTest#testBasicUriWithSettingsGeneration
      
      
      
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
